import styled from "styled-components";

const Container = styled.div`
  height: 100%;
  min-height: 90vh;
  padding: 60px 40px 40px;
`;

export const HomePage = (): JSX.Element => (
  <Container>
    <p>
      Welcome to GraphMaven, a responsive website that I've built as one of my
      personal projects. Written in TypeScript using Next.js, it leverages
      Material UI and Styled Components to create an online graph-making tool.
    </p>
    <p>
      The following paragraphs were generated by ChatGPT to help fill the space.
      They have been edited for clarity and conciseness.
    </p>
    <p>
      At GraphMaven, we're passionate about creating visually captivating graphs
      that bring data to life. Our platform combines user-friendly design with
      powerful graph-making tools to help you create stunning visualizations
      effortlessly. From bar graphs to pie charts, our diverse range of graph
      types caters to all your data visualization needs. With easy customization
      options, you can create graphs that truly stand out.
    </p>
    <p>
      But we don't stop at static images. GraphMaven takes your graphs to the
      next level with animated elements that add a dynamic and engaging touch.
      When you're ready to share or showcase your graphs, you can easily
      download high-quality images in various formats.
    </p>
  </Container>
);
